plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.kanaquiz'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.kanaquiz'
        minSdk 23
        targetSdk 35
        versionCode 15
        versionName "15.0"
    }

    buildTypes {
        debug {
            debuggable true
        }
    }
}

dependencies {
}
